plugins:
  - jekyll-include-cache
theme: minima

site.title: Texploring
site.author.name: Anurag Setia
title: Texploring | Anurag Setia
description: "Anurag Setia's blog about technology and some..."

header_pages:
  - about.md
  - covid19.md
show_excerpts: true

google_analytics: G-J80TT227HM
