plugins:
  - jekyll-include-cache
  - jekyll-feed
theme: minima

site.title: Texploring
site.author.name: Anurag Setia
title: Texploring
description: "Anurag Setia's blog about technology and some..."

header_pages:
  - about.md
show_excerpts: true

google_analytics: G-J80TT227HM
